Repository facebookresearch/TensorComprehensions, pull requests merged in 2018-04, with the labels that each got.

#242 docs: minor spelling tweaks
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/framework/pytorch_integration/note_about_performance.rst
  docs/source/integrating_any_ml_framework.rst
Labels: CLA Signed

#246 some cleanups to codegen_llvm.cc
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#251 cuda/codegen.cc: drop dead code
  src/core/polyhedral/cuda/codegen.cc
Labels: CLA Signed

#252 drop test_isl_functionality.cc test
  test/CMakeLists.txt
  test/test_isl_functionality.cc
Labels: CLA Signed

#253 reduction_matcher.cc: clean up reduction detection
  src/core/polyhedral/reduction_matcher.cc
Labels: CLA Signed

#226 emitHalideExpr: print parentheses around compound nested expressions
  include/tc/core/polyhedral/cuda/codegen.h
  src/core/polyhedral/cuda/codegen.cc
  test/test_mapper.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#248 Use const pointers for input tensors in generated cuda
  include/tc/lang/sema.h
  src/core/polyhedral/cuda/codegen.cc
  test/test_mapper.cc
  test/test_tc2halide.cc
Labels: CLA Signed

#255 caffe2 test fix + validation
  test_python/test_c2.py
Labels: CLA Signed

#244 unit test for mul reduction, use pytest + gen=2/pop=1 to improve test time
  .gitignore
  .jenkins/build.sh
  tensor_comprehensions/tc_unit.py
  test_python/layers/test_matmul_train.py
  test_python/layers/test_multiply_reduction.py
  test_python/run_test.sh
Labels: CLA Signed

#256 tc_format.cc: avoid unused variable warning
  src/lang/tc_format.cc
Labels: CLA Signed

#257 drop unused "mu wrappers"
  include/tc/external/detail/isl_mu_wrappers.h
Labels: CLA Signed

#258 tightenLaunchBounds: minor simplification
  src/core/polyhedral/cuda/tighten_launch_bounds.cc
Labels: CLA Signed

#215 TC coding guide
  CodingConventions.md
  benchmarks/MLP_model.cc
  benchmarks/batchmatmul.cc
  benchmarks/group_convolution.cc
  benchmarks/tmm.cc
  docs/doxygen/index.md
  docs/source/coding_conventions.rst
  docs/source/framework/caffe2_integration/integration_with_example.rst
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/framework/pytorch_integration/autotuning_layers.rst
  docs/source/framework/pytorch_integration/frequently_asked_questions.rst
  docs/source/framework/pytorch_integration/getting_started.rst
  docs/source/framework/pytorch_integration/layers_database.rst
  docs/source/framework/pytorch_integration/note_about_performance.rst
  docs/source/framework/pytorch_integration/writing_layers.rst
  docs/source/index.rst
  docs/source/inference.rst
  docs/source/introduction.rst
  docs/source/ml_with_tc.rst
  docs/source/tutorials/tutorial_tensordot_with_tc.rst
  tensor_comprehensions/library/layers.yaml
  test/test_autotuner.cc
  test/test_autotuner_utility.cc
  test/test_caffe2.cc
  test/test_compilation_cache.cc
  test/test_core.cc
  test/test_execution_engine.cc
  test/test_execution_engine_cache.cc
  test/test_execution_engine_db.cc
  test/test_mapper.cc
  test/test_mapper_llvm.cc
  test/test_mapper_memory_promotion.cc
  test/test_tc_mapper.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#260 ScheduleTreeElemContext::write: do not treat context as union set
  src/core/polyhedral/schedule_print.cc
Labels: CLA Signed

#259 Use canonicalized TC as part of cache keys
  include/tc/autotuner/utils/utils.h
  include/tc/core/tc_executor.h
  src/autotuner/genetic_autotuner.cc
  src/autotuner/utils/utils.cc
  src/core/cuda/cuda_tc_executor.cc
  src/core/tc_executor.cc
  test/test_autotuner_utility.cc
  test/test_tc_mapper.cc
Labels: CLA Signed

#261 Fix and reactivate 1-D reduction tests
  include/tc/core/utils/dlpack-inl.h
  test/test_tc_mapper.cc
Labels: CLA Signed, review me

#273 Drop default cache filename
  include/tc/core/flags.h
  src/core/flags.cc
  tensor_comprehensions/pybinds/pybind_autotuner.cc
Labels: CLA Signed

#268 rename *Idxx* to *IdxX*
  include/tc/core/polyhedral/cuda/mapped_scop.h
  include/tc/core/polyhedral/cuda/memory_promotion_heuristic.h
  src/core/polyhedral/cuda/mapped_scop.cc
  src/core/polyhedral/cuda/memory_promotion_heuristic.cc
  test/test_mapper_memory_promotion.cc
Labels: CLA Signed

#265 remove code that depends on order of parameters in isl objects
  include/tc/core/polyhedral/scop.h
  include/tc/external/detail/islpp.h
  test/test_mapper.cc
  test/test_mapper_memory_promotion.cc
Labels: CLA Signed

#282 Fix broken python tests on CI
  docs/source/autotuner.rst
  tensor_comprehensions/tc_unit.py
Labels: CLA Signed, review me

#264 Fix bug introduced by #259
  benchmarks/benchmark_fixture.h
  include/tc/autotuner/utils/utils.h
  include/tc/core/tc_executor.h
  include/tc/lang/canonicalize.h
  src/autotuner/genetic_autotuner.cc
  src/autotuner/utils/utils.cc
  src/core/cuda/cuda_tc_executor.cc
  src/core/tc_executor.cc
  test/cuda/test_autotuner_utility.cc
  test/test_lang.cc
  test/test_tc_mapper_harness-inl.h
Labels: CLA Signed

#277 codegen_llvm.cc: include proper header for makeIslAffFromExpr declaration
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#278 Scop::makeContextFromInputs: fix check for fixed parameter values
  src/core/polyhedral/scop.cc
Labels: CLA Signed

#286 emitCudaKernel: avoid relying on isl set variable names
  include/tc/core/polyhedral/cuda/codegen.h
  src/core/polyhedral/cuda/codegen.cc
Labels: CLA Signed

#228 Add a blockdiagperm example for @pierrestock
  examples/CMakeLists.txt
  examples/blockdiagperm.cc
  examples/tensordot.cc
  include/tc/core/cuda/cuda.h
  src/core/cuda/cuda.cc
  test/test_harness.h
Labels: CLA Signed

#235 Add a fused 2 layer wavenet example
  examples/CMakeLists.txt
  examples/blockdiagperm.cc
  examples/tensordot.cc
  examples/wavenet.cc
  src/core/cuda/cuda_rtc.cc
Labels: CLA Signed

#270 Parser rules for min/max
  include/tc/lang/parser.h
  test/cuda/test_corner_cases.cc
Labels: CLA Signed

#275 Refactor caches
  tc/autotuner/utils/utils.cc
  tc/core/CMakeLists.txt
  tc/core/compilation_cache.cc
  tc/core/compilation_cache.h
  tc/core/cuda/cuda_compilation_cache-inl.h
  tc/core/cuda/cuda_compilation_cache.cc
  tc/core/cuda/cuda_compilation_cache.h
  tc/core/cuda/cuda_mapping_options.h
  tc/core/cuda/cuda_tc_executor.cc
  tensor_comprehensions/pybinds/pybind_engine.cc
  test/CMakeLists.txt
  test/cuda/test_compilation_cache.cc
  test/test_cuda_mapper.cc
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#280 Expose option for saving # best candidates in autotuning
  tc/autotuner/genetic_autotuner.cc
  tc/core/flags.cc
  tc/core/flags.h
  tensor_comprehensions/pybinds/pybind_autotuner.cc
  tensor_comprehensions/tc_unit.py
Labels: CLA Signed, review me

#284 Enable Werror compiler flag
  CMakeLists.txt
  tc/lang/lexer.h
Labels: CLA Signed, review me

#295 Move protobufs generated files to tc/proto/*.{h/cc}
  .gitignore
  tc/core/compilation_cache.h
  tc/core/cpu/cpu_mapping_options.h
  tc/core/cuda/cuda_compilation_cache.h
  tc/core/cuda/cuda_mapping_options.cc
  tc/core/cuda/cuda_mapping_options.h
  tc/core/mapping_options.cc
  tc/core/mapping_options.h
  tc/proto/CMakeLists.txt
Labels: CLA Signed

#283 Don't split reductions to remove nested thread mapping
  tc/core/polyhedral/cuda/mapped_scop.cc
  tc/core/polyhedral/cuda/mapped_scop.h
Labels: CLA Signed, review me

#299 CudaRTCFunction: do not unload the module that was never loaded
  tc/core/cuda/cuda_rtc.cc
Labels: CLA Signed

#301 do not promote to registers before promoting to shared in tests
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#303 MappedScop::mapToThreads: fix depth of threadIdxX in case of reduction
  tc/core/polyhedral/cuda/mapped_scop.cc
Labels: CLA Signed

#310 Sum4D.CodeBeforeThreadMapping: perform promotion above thread mapping again
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#304 fix typos in comments
  tc/core/polyhedral/cuda/mapped_scop.cc
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/memory_promotion.cc
  tc/core/polyhedral/schedule_transforms.h
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#297 Reduce dependency in genetic_autotuner.h
  tc/autotuner/genetic_autotuner.h
  tc/autotuner/genetic_tuning_harness.h
  tc/autotuner/utils/utils.h
  test/cuda/test_autotuner_utility.cc
Labels: CLA Signed

#298 Fix serializeToProtobuf method of Options
  tensor_comprehensions/pybinds/pybind_options.cc
Labels: CLA Signed

#311 Make Wno-sign-compare flag non-caffe2 specific
  CMakeLists.txt
Labels: CLA Signed

#317 shut up some comparison between signed and unsigned integer expressions warnings
  CMakeLists.txt
  tc/aten/aten_compiler-inl.h
  tc/autotuner/genetic_autotuner.cc
  tc/autotuner/genetic_search.cc
  tc/autotuner/genetic_tuning_harness.cc
  tc/autotuner/genetic_tuning_harness.h
  tc/autotuner/parameters.cc
  tc/benchmarks/benchmark_fixture.h
  tc/c2/tc_op.h
  tc/core/cuda/cuda_mapping_options-inl.h
  tc/core/cuda/cuda_mapping_options.cc
  tc/core/cuda/cuda_rtc.cc
  tc/core/cuda/cuda_tc_executor.cc
  tc/core/execution_engine-inl.h
  tc/core/halide2isl.cc
  tc/core/halide2isl.h
  tc/core/halide_utils.cc
  tc/core/mapping_options-inl.h
  tc/core/polyhedral/codegen_llvm.cc
  tc/core/polyhedral/cuda/codegen.cc
  tc/core/polyhedral/cuda/mapped_scop.cc
  tc/core/polyhedral/cuda/mapped_scop.h
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/llvm_jit.cc
  tc/core/polyhedral/memory_promotion.cc
  tc/core/polyhedral/memory_promotion.h
  tc/core/polyhedral/reduction_matcher.cc
  tc/core/polyhedral/schedule_isl_conversion.cc
  tc/core/polyhedral/schedule_transforms-inl.h
  tc/core/polyhedral/schedule_transforms.cc
  tc/core/polyhedral/schedule_transforms.h
  tc/core/polyhedral/schedule_tree-inl.h
  tc/core/polyhedral/schedule_tree.cc
  tc/core/polyhedral/schedule_tree.h
  tc/core/polyhedral/schedule_tree_elem.cc
  tc/core/polyhedral/schedule_tree_elem.h
  tc/core/polyhedral/scop.cc
  tc/core/polyhedral/scop.h
  tc/core/tc_executor.cc
  tc/examples/wavenet.cc
  tc/lang/builtins.h
  tc/lang/tree.h
  test/cuda/test_autotuner_utility.cc
  test/cuda/test_compilation_cache.cc
  test/test_cuda_mapper.cc
  test/test_cuda_mapper_memory_promotion.cc
  test/test_harness_aten_cuda.h
  test/test_mapper_tapir.cc
Labels: CLA Signed

#321 fix typos
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/memory_promotion.cc
  tc/core/polyhedral/schedule_isl_conversion.cc
Labels: CLA Signed

#336 extract out generic insertNode{Above,Below}
  tc/core/polyhedral/cuda/mapped_scop.cc
  tc/core/polyhedral/schedule_transforms-inl.h
  tc/core/polyhedral/schedule_transforms.cc
  tc/core/polyhedral/schedule_transforms.h
  tc/core/polyhedral/scop.cc
Labels: CLA Signed

#320 insertCopiesUnder: use insertExtension{Before,After}
  tc/core/polyhedral/memory_promotion.cc
  tc/core/polyhedral/schedule_isl_conversion.cc
  tc/core/polyhedral/schedule_transforms.cc
  tc/core/polyhedral/schedule_transforms.h
  tc/core/polyhedral/schedule_tree.cc
  tc/core/polyhedral/schedule_tree.h
Labels: CLA Signed

#312 Add instuctions for building TC with PyTorch master build
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
Labels: CLA Signed, docs, review me

#340 Fix MappingOptionsPrinter
  tc/core/cuda/cuda_mapping_options_cpp_printer.cc
  tc/core/cuda/cuda_mapping_options_cpp_printer.h
  tc/core/mapping_options.cc
  tc/core/mapping_options_cpp_printer.cc
  tc/core/mapping_options_cpp_printer.h
Labels: CLA Signed

#325 Warning for uninitialized reductions.
  tc/lang/sema.h
  test/test_lang.cc
Labels: CLA Signed

#337 build.sh fixes
  build.sh
Labels: CLA Signed

#335 explicitly mention requirement for commit messages in CodingConvention.md
  CodingConventions.md
Labels: CLA Signed

#341 TC: Sync fbcode to github
  tensor_comprehensions/pybinds/pybind_options.cc
  test_python/test_c2.py
Labels: CLA Signed

#350 Fix the autotuner benchmark scripts following folders merge
  tc/benchmarks/scripts/AUTOTUNER_COMMANDS
  tc/benchmarks/scripts/autotuner_parallel.sh
Labels: CLA Signed

#349 Activate conda env which has TC build for test time
  .jenkins/run_test.sh
Labels: CLA Signed

#327 Remove C2 overhead
  tc/c2/tc_op.h
Labels: CLA Signed

#353 [C++ API] Step 1: drop manual and compilation caches
  docs/source/framework/pytorch_integration/writing_layers.rst
  tc/autotuner/genetic_autotuner.cc
  tc/autotuner/genetic_autotuner_aten.cc
  tc/autotuner/genetic_tuning_harness.cc
  tc/benchmarks/benchmark_fixture.h
  tc/core/cuda/cuda_compilation_cache.cc
  tc/core/cuda/cuda_compilation_cache.h
  tc/core/cuda/cuda_tc_executor.cc
  tc/proto/compcache.proto
  tensor_comprehensions/pybinds/pybind_engine.cc
  tensor_comprehensions/tc_unit.py
  test/cuda/test_autotuner_utility.cc
  test/cuda/test_caffe2.cc
  test/cuda/test_compilation_cache.cc
  test/cuda/test_tc_mapper.cc
  test/test_tc_mapper_harness-inl.h
  test_python/layers/test_external_cuda_injection.py
  test_python/test_tc_torch.py
Labels: CLA Signed

#344 replace ThreadIdxXScheduleDepthState by thread specific markers
  tc/core/polyhedral/cuda/mapped_scop.cc
  tc/core/polyhedral/cuda/mapped_scop.h
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/cuda/memory_promotion_heuristic.h
  tc/core/polyhedral/schedule_isl_conversion.cc
  tc/core/polyhedral/schedule_print.cc
  tc/core/polyhedral/schedule_tree.cc
  tc/core/polyhedral/schedule_tree.h
  tc/core/polyhedral/schedule_tree_elem.cc
  tc/core/polyhedral/schedule_tree_elem.h
  tc/external/detail/islpp.h
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#355 insertCopiesUnder: drop iteration over tensor dimensions of size 1 up front
  tc/core/polyhedral/cuda/codegen.cc
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/memory_promotion.cc
  tc/core/polyhedral/scop.cc
  tc/core/polyhedral/scop.h
Labels: CLA Signed

#358 Use gcc 5.4 on xenial non-conda + use pytorch 0.4 official + fix broken python API
  .jenkins/build.sh
  docker/README.md
  docker/common/install_base.sh
  tensor_comprehensions/tc_unit.py
  test_python/test_tc.py
  test_python/test_tc_torch.py
Labels: CLA Signed

#364 Cleanup cache .cuda artifacts and more fixes to python test
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/framework/pytorch_integration/autotuning_layers.rst
  tc/autotuner/genetic_autotuner.cc
  tc/benchmarks/benchmark_fixture.h
  tc/core/compilation_cache.h
  test_python/layers/test_autotuner.py
Labels: CLA Signed

#354 Reduce unrolling factors during tuning
  tc/autotuner/genetic_tuning_harness.cc
Labels: CLA Signed

#368 isPromotableToRegisterBelowThreads: directly use relevant parts of schedule
  tc/core/polyhedral/cuda/memory_promotion_heuristic.cc
  tc/core/polyhedral/schedule_transforms.cc
  tc/core/polyhedral/schedule_transforms.h
Labels: CLA Signed

#326 TC: Compilation fix for -Werror=shadow-compatible-local
  tc/autotuner/genetic_search.cc
  tc/core/halide2isl.cc
  tc/core/polyhedral/schedule_transforms.cc
  tc/core/polyhedral/schedule_tree.cc
  tc/core/tc2halide.cc
Labels: CLA Signed

#373 Scop::getParameterValues: extract parameter values directly from context
  tc/core/polyhedral/scop.cc
  tc/external/detail/isl_mu_wrappers.h
  tc/external/isl.h
Labels: CLA Signed

#374 test_cuda_mapper_memory_promotion.cc: drop explicit parameter name setting
  test/test_cuda_mapper_memory_promotion.cc
Labels: CLA Signed

#359 [C++ API] Step 2: add the new compiler files
  tc/core/compiler-inl.h
  tc/core/compiler.cc
  tc/core/compiler.h
Labels: CLA Signed

#375 further restrict line size in commit messages
  CodingConventions.md
Labels: CLA Signed
