Repository facebookresearch/TensorComprehensions, pull requests merged in 2018-02, with the labels that each got.

#4 update arXiv links
  docs/source/performance.rst
  docs/source/report.rst
Labels: CLA Signed

#5 adding arXiv link to readme + small improvements to readme
  README.md
Labels: CLA Signed

#6 Fix e-mail address in docs
  docs/source/report.rst
Labels: CLA Signed

#8 [generated docs] update Theodoros' email address
  _sources/report.rst.txt
  report.html
Labels: CLA Signed

#13 update slack auto-invite link
  README.md
  docs/source/contacts.rst
Labels: CLA Signed

#14 readme update for slack link
  README.md
Labels: CLA Signed

#15 minor sp in docs
  docs/source/ml_with_tc.rst
  docs/source/semantics.rst
Labels: CLA Signed

#17 Add test case for concat operation
  test/test_execution_engine.cc
Labels: CLA Signed

#21 Fix typo in matrix-multiply example.
  docs/source/introduction.rst
Labels: CLA Signed

#19 Update docs and write about temporaties explicitly
  docs/source/docker_image.rst
  docs/source/installation.rst
  docs/source/ml_with_tc.rst
Labels: CLA Signed

#24 Avoid reconstructing HalideComponents from TC lang
  src/core/tc_executor.cc
Labels: CLA Signed

#32 mention `!` in semantics description
  docs/source/semantics.rst
Labels: CLA Signed

#31 fix typo in introduction.rst
  docs/source/introduction.rst
Labels: CLA Signed

#36 Regenerate docs with fixes
  docs/source/introduction.rst
  docs/source/semantics.rst
Labels: CLA Signed

#33 .gitsubmodule paths and instructions for cloning should be https not ssh
  .gitmodules
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
  docs/source/installation_non_conda.rst
Labels: CLA Signed

#37 Update install TC from docker instructions
  docs/source/index.rst
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
  docs/source/installation_docker_image.rst
  docs/source/installation_non_conda.rst
Labels: CLA Signed

#28 Implement where clause variables and exists
  docs/source/inference.rst
  include/tc/core/libraries.h
  include/tc/lang/lexer.h
  include/tc/lang/parser.h
  include/tc/lang/sema.h
  include/tc/lang/tree.h
  include/tc/lang/tree_views.h
  src/core/tc2halide.cc
  test/test_corner_cases.cc
  test/test_execution_engine.cc
  test/test_lang.cc
Labels: CLA Signed

#40 Update Tapir in docker images
  .circleci/config.yml
Labels: CLA Signed, review me

#38 Add github issues template
  .github/ISSUE_TEMPLATE.md
Labels: CLA Signed, review me

#42 Add cilk runtime to docker images
  docker/linux-trusty-gcc4.8-tapir5.0/Dockerfile
  docker/linux-xenial-gcc5-tapir5.0/Dockerfile
Labels: CLA Signed

#43 Update docs install instructions, docker images and github issue template
  .github/ISSUE_TEMPLATE.md
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
  docs/source/installation_docker_image.rst
  docs/source/installation_non_conda.rst
Labels: CLA Signed, review me

#47 Add Doxyfile
  docs/doxygen/Doxyfile
  docs/doxygen/index.md
  docs/doxygen/tc-logo-small.png
Labels: CLA Signed

#50 Config changes, README for doxygen docs, hosted docs
  docs/README.md
  docs/doxygen/Doxyfile
  docs/doxygen/img/tc-logo-small.png
  docs/doxygen/index.md
  docs/source/installation_caffe2_integration.rst
Labels: CLA Signed

#59 Caffe2Test.TcConvolutionOp_Gradient (disabled): drop check for error
  test/test_caffe2.cc
Labels: CLA Signed

#51 Fix extractAccess to process each IRNode once
  src/core/halide2isl.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#57 Add a check for use of temporary tensors
  include/tc/lang/sema.h
  test/test_corner_cases.cc
Labels: CLA Signed

#60 cmake: use HINTS instead of PATHS to prefer custom gflags and glog
  CMakeLists.txt
Labels: CLA Signed

#64 Remove Halide functionality used for generating input to PPCG
  include/tc/core/halide2pencil.h
  include/tc/core/halide_utils.h
  include/tc/core/tc_executor.h
  src/core/CMakeLists.txt
  src/core/halide2pencil.cc
  src/core/halide_utils.cc
  src/core/tc2halide.cc
  src/core/tc_executor.cc
  test/test_core.cc
Labels: CLA Signed

#66 Update dockerfiles to enable LLVM exception handling variable
  docker/linux-trusty-gcc4.8-tapir5.0/Dockerfile
  docker/linux-xenial-gcc5-tapir5.0/Dockerfile
  docs/source/installation_conda.rst
  docs/source/installation_non_conda.rst
Labels: CLA Signed

#67 Cleanly handle SIGINT for autotuner and add layernorm test
  include/tc/autotuner/genetic_tuning_harness.h
  include/tc/library/dper_lut_concat.h
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_tuning_harness.cc
  test/test_autotuner.cc
  test/test_caffe2.cc
Labels: CLA Signed

#69 Improve imports in lang namespace
  include/tc/lang/parser.h
  include/tc/lang/tree_views.h
Labels: CLA Signed

#61 Add a unit test for softmax
  test/test_execution_engine.cc
Labels: CLA Signed

#70 TcExecutor: remove useless declarations
  include/tc/core/tc_executor.h
Labels: CLA Signed

#71 remove some unused functions
  include/tc/external/detail/islpp-inl.h
  include/tc/external/detail/islpp.h
Labels: CLA Signed

#75 Documentation for PyTorch Integration with Tensor Comprehensions
  docs/source/aten_integration.rst
  docs/source/autotuner.rst
  docs/source/conf.py
  docs/source/framework/caffe2_integration/installation_caffe2_integration.rst
  docs/source/framework/caffe2_integration/integration_with_example.rst
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/framework/pytorch_integration/autotuning_layers.rst
  docs/source/framework/pytorch_integration/debugging.rst
  docs/source/framework/pytorch_integration/frequently_asked_questions.rst
  docs/source/framework/pytorch_integration/getting_started.rst
  docs/source/framework/pytorch_integration/layers_database.rst
  docs/source/framework/pytorch_integration/note_about_performance.rst
  docs/source/framework/pytorch_integration/writing_layers.rst
  docs/source/index.rst
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
  docs/source/installation_non_conda.rst
  docs/source/integrating_any_ml_framework.rst
  docs/source/introduction.rst
  docs/source/mapping_options.rst
  docs/source/ml_with_tc.rst
Labels: CLA Signed, framework, high-pri, review me

#81 Correctly check the autotuner cache file exists
  tensor_comprehensions/tc_unit.py
Labels: CLA Signed, review me

#80 Adding a tutorial using TensorDot operation
  docs/source/_static/img/autotuning-py.jpg
  docs/source/framework/pytorch_integration/autotuning_layers.rst
  docs/source/index.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/tutorial_tensordot_with_tc.rst
Labels: CLA Signed, review me

#83 Small improvement to parameters init fit autotuner
  tensor_comprehensions/tc_unit.py
  test_python/test_tc_torch.py
Labels: CLA Signed

#84 Update version to v0.1.1
  conda_recipes/conda_build_tc.sh
  setup.py
Labels: CLA Signed

#39 Abstract away ExecutionEngine from CUDA
  CMakeLists.txt
  build.sh
  examples/example_MLP_model.cc
  examples/example_batchmatmul.cc
  examples/example_group_convolution.cc
  examples/example_tmm.cc
  include/tc/aten/aten_compiler.h
  include/tc/autotuner/genetic_tuning_harness.h
  include/tc/autotuner/parameters.h
  include/tc/c2/tc_op.h
  include/tc/core/compilation_cache.h
  include/tc/core/cuda.h
  include/tc/core/cuda/cuda_execution_engine.h
  include/tc/core/cuda/cuda_tc_executor.h
  include/tc/core/execution_engine.h
  include/tc/core/gpu.h
  include/tc/core/halide_utils.h
  include/tc/core/mapping_options.h
  include/tc/core/rtc.h
  include/tc/core/tc_executor.h
  include/tc/core/utils/cuda_info.h
  include/tc/core/utils/time.h
  src/CMakeLists.txt
  src/aten/aten_compiler.cc
  src/autotuner/CMakeLists.txt
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_tuning_harness.cc
  src/c2/register.cc
  src/core/CMakeLists.txt
  src/core/cuda.cc
  src/core/cuda/cuda_execution_engine.cc
  src/core/cuda/cuda_tc_executor.cc
  src/core/execution_engine.cc
  src/core/halide_utils.cc
  src/core/mapping_options.cc
  src/core/polyhedral/mapped_scop.cc
  src/core/tc_executor.cc
  src/core/utils/cuda_info.cc
  tensor_comprehensions/pybinds/CMakeLists.txt
  test/CMakeLists.txt
  test/test_autotuner.cc
  test/test_compilation_cache.cc
  test/test_core.cc
  test/test_corner_cases.cc
  test/test_execution_engine.cc
  test/test_execution_engine_cache.cc
  test/test_execution_engine_db.cc
  test/test_harness_aten.h
  test/test_harness_aten_cuda.h
  test/test_tc_mapper.cc
  test/test_tc_mapper_bugs.cc
  test_cpu.sh
Labels: CLA Signed

#86 add small notes to autograd tc tutorial
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/tutorials/tutorial_tensordot_with_tc.rst
Labels: CLA Signed

#87 nits and docs fixes for mobile docs
  docs/source/_static/css/tc_theme.css
  docs/source/conf.py
  docs/source/framework/pytorch_integration/layers_database.rst
  docs/source/tutorials/tutorial_tensordot_with_tc.rst
Labels: CLA Signed

#88 Python support via pybind currently can only work in CUDA mode.
  CMakeLists.txt
Labels: CLA Signed
