Repository facebookresearch/TensorComprehensions, pull requests merged in 2018-03, with the labels that each got.

#92 Update the conda hash corresponding to v0.1.1
  conda_recipes/conda_build_tc.sh
Labels: CLA Signed, review me

#90 Paths and build system cleanups
  CMakeLists.txt
  build.sh
  examples/example_MLP_model.cc
  examples/example_batchmatmul.cc
  examples/example_fixture.h
  examples/example_group_convolution.cc
  examples/example_tmm.cc
  include/tc/aten/aten_compiler.h
  include/tc/autotuner/utils/printer.h
  include/tc/autotuner/utils/utils.h
  include/tc/c2/context.h
  include/tc/c2/tc_op.h
  include/tc/core/cuda/cuda.h
  include/tc/core/cuda/cuda_compilation_cache.h
  include/tc/core/cuda/cuda_rtc.h
  include/tc/core/cuda/cuda_tc_executor.h
  include/tc/core/gpu.h
  include/tc/core/halide2isl.h
  include/tc/core/polyhedral/codegen_llvm.h
  include/tc/core/tc2halide.h
  src/CMakeLists.txt
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_autotuner_aten.cc
  src/autotuner/genetic_tuning_harness.cc
  src/autotuner/utils/utils.cc
  src/core/CMakeLists.txt
  src/core/cuda/cuda.cc
  src/core/cuda/cuda_compilation_cache.cc
  src/core/cuda/cuda_rtc.cc
  src/core/cuda/cuda_tc_executor.cc
  src/core/polyhedral/codegen_llvm.cc
  tensor_comprehensions/pybinds/pybind_engine.cc
  test/test_autotuner_utility.cc
  test/test_basic_gpu.cc
  test/test_compilation_cache.cc
  test/test_harness.h
  test/test_harness_aten_cuda.h
  test/test_tc_mapper.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#95 Matmul grad
  docs/source/framework/pytorch_integration/layers_database.rst
  tensor_comprehensions/library/layers.yaml
  test_python/layers/test_matmul_train.py
Labels: CLA Signed

#100 Make few things explicit - package distr and cuda() for tensors
  docs/source/framework/pytorch_integration/autograd_with_tc.rst
  docs/source/framework/pytorch_integration/getting_started.rst
Labels: CLA Signed, review me

#101 Use tensorcomp conda channel for install
  conda_recipes/conda_build_c2.sh
  docs/source/framework/caffe2_integration/installation_caffe2_integration.rst
  docs/source/framework/pytorch_integration/getting_started.rst
  docs/source/installation_conda.rst
  docs/source/installation_conda_dep.rst
  docs/source/tutorials/tutorial_tensordot_with_tc.rst
Labels: CLA Signed, review me

#105 Fix typo in github issues template
  .github/ISSUE_TEMPLATE.md
Labels: CLA Signed

#106 mapped_scop.cc: fix typos in comment
  src/core/polyhedral/mapped_scop.cc
Labels: CLA Signed

#110 Make the warning explicit that its a warning
  include/tc/lang/error_report.h
Labels: CLA Signed, review me

#111 [Hotfix] Temporarily make dump-cuda flag dump to cout
  src/core/tc_executor.cc
Labels: CLA Signed, review me

#112 int to int32 in docs
  docs/source/semantics.rst
Labels: CLA Signed

#115 [Hotfix] emit macros for inf/inff
  docs/source/framework/pytorch_integration/layers_database.rst
  include/tc/core/libraries.h
  src/core/polyhedral/mapped_scop.cc
  test/test_execution_engine.cc
  test_python/layers/test_softmax.py
Labels: CLA Signed

#114 Update the master hash and refresh conda packages
  conda_recipes/conda_build_tc.sh
Labels: CLA Signed

#118 Add unit test for broadcasted fcrelu
  test_python/layers/test_broadcast_fcrelu.py
  test_python/run_test.sh
Labels: CLA Signed, review me

#120 Log exception rather than just passing
  tensor_comprehensions/tc_unit.py
Labels: CLA Signed

#121 Update conda hash for refreshed packages
  conda_recipes/conda_build_tc.sh
Labels: CLA Signed, review me

#102 Cleanups towards CPU mapper
  include/tc/aten/aten_compiler.h
  include/tc/autotuner/genetic_tuning_harness.h
  include/tc/c2/tc_op.h
  include/tc/core/cuda/cuda_execution_engine.h
  include/tc/core/cuda/cuda_tc_executor.h
  include/tc/core/execution_engine-inl.h
  include/tc/core/execution_engine.h
  include/tc/core/flags.h
  include/tc/core/tc_executor.h
  src/aten/aten_compiler.cc
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_tuning_harness.cc
  src/core/CMakeLists.txt
  src/core/cuda/cuda_execution_engine.cc
  src/core/cuda/cuda_tc_executor.cc
  src/core/execution_engine.cc
  src/core/flags.cc
  src/core/polyhedral/codegen_llvm.cc
  src/core/tc_executor.cc
  test/test_mapper_llvm.cc
Labels: CLA Signed

#134 ScheduleTree: delclare function before declaring it as friend
  include/tc/core/polyhedral/schedule_tree.h
Labels: CLA Signed

#135 Relax cuda/cudnn version requirement
  examples/README.md
  examples/example_fixture.h
  examples/scripts/AUTOTUNER_COMMANDS
  test.sh
Labels: CLA Signed, high-pri, review me

#136 Fix the version check inequality
  examples/example_fixture.h
Labels: CLA Signed, review me

#122 Refactor dockerfiles and install jenkins user
  .jenkins/build.sh
  .jenkins/run_test.sh
  docker/README.md
  docker/archive/linux-trusty-gcc4.8-cuda8-cudnn6-py3-conda/Dockerfile
  docker/archive/linux-trusty-gcc4.8-cuda8-cudnn6-py3/Dockerfile
  docker/archive/linux-xenial-gcc5-cuda9-cudnn7-py3-conda/Dockerfile
  docker/archive/linux-xenial-gcc5-cuda9-cudnn7-py3/Dockerfile
  docker/common/add_jenkins_user.sh
  docker/common/install_base.sh
  docker/common/install_conda.sh
  docker/common/install_cuda.sh
  docker/common/install_pip_python.sh
  docker/common/install_protobuf.sh
  docker/docker_build.sh
  docker/ubuntu-cuda-conda/Dockerfile
  docker/ubuntu-cuda/Dockerfile
Labels: CLA Signed, high-pri, review me

#140 Fix small errors in Jenkins CI docker
  .jenkins/build.sh
  docker/common/add_jenkins_user.sh
  docker/ubuntu-cuda-conda/Dockerfile
Labels: CLA Signed, high-pri, review me

#143 Explicitly denote message is a warning
  include/tc/core/compilation_cache-inl.h
Labels: CLA Signed, review me

#145 do not emit semicolon after if_then_else macro
  include/tc/core/libraries.h
Labels: review me

#146 Harden conda install check
  .jenkins/build.sh
  .jenkins/run_test.sh
  build.sh
Labels: CLA Signed, high-pri, review me

#138 More cleanups towards a CPU path
  examples/CMakeLists.txt
  examples/example_fixture.h
  include/tc/aten/aten_compiler-inl.h
  include/tc/aten/aten_compiler.h
  include/tc/aten/utils-inl.h
  include/tc/aten/utils.h
  include/tc/core/cpu/cpu_tc_executor.h
  include/tc/core/execution_engine-inl.h
  include/tc/core/execution_engine.h
  include/tc/core/tc_executor.h
  src/CMakeLists.txt
  src/aten/CMakeLists.txt
  src/autotuner/CMakeLists.txt
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_autotuner_aten.cc
  src/core/CMakeLists.txt
  src/core/cpu/cpu_tc_executor.cc
  tensor_comprehensions/pybinds/CMakeLists.txt
  tensor_comprehensions/pybinds/pybind_engine.cc
  test/CMakeLists.txt
  test/test_autotuner.cc
  test/test_autotuner_utility.cc
  test/test_compilation_cache.cc
  test/test_corner_cases.cc
  test/test_execution_engine.cc
  test/test_execution_engine_cache.cc
  test/test_execution_engine_db.cc
  test/test_harness_aten_cuda.h
  test/test_mapper_llvm.cc
  test/test_tc_mapper.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#147 Allow Jenkins to write to root conda env
  docker/common/add_jenkins_user.sh
  docker/ubuntu-cuda-conda/Dockerfile
Labels: CLA Signed, high-pri, review me

#150 Recursive chown and create a conda env
  .jenkins/build.sh
  .jenkins/run_test.sh
  docker/common/add_jenkins_user.sh
Labels: CLA Signed, high-pri, review me

#127 [hotfix] Support min max bounds
  src/core/halide2isl.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#152 Try small size for 2LUT test cases
  examples/example_MLP_model.cc
Labels: CLA Signed, review me

#151 filter PLDI 2LUT tests temporarily from CI
  .jenkins/run_test.sh
Labels: CLA Signed, review me

#139 Patch for vanilla LLVM
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#157 Fix compilation issue: prevents copy elision
  test/test_harness.h
Labels: CLA Signed

#153 Install and compile with ccache for faster builds
  docker/common/install_base.sh
  docker/docker_build.sh
  docker/ubuntu-cuda-conda/Dockerfile
  docker/ubuntu-cuda/Dockerfile
Labels: CLA Signed, high-pri, review me

#156 Fix compilation issue: braces around scalar initializer
  include/tc/c2/copy_op.h
  test/test_basic.cc
Labels: CLA Signed

#154 Fix compilation issue: has virtual functions but non-virtual destructor
  include/tc/lang/tree.h
Labels: CLA Signed

#158 use ccache in c2 build if installed
  build.sh
Labels: CLA Signed, review me

#159 fix flaky errors in trusty conda docker image
  docker/common/install_base.sh
  docker/ubuntu-cuda-conda/Dockerfile
  docker/ubuntu-cuda/Dockerfile
Labels: CLA Signed, review me

#163 Use correct ccache repo path
  build.sh
Labels: CLA Signed

#166 Add pybindings for gflags
  docs/source/framework/pytorch_integration/debugging.rst
  include/tc/core/flags.h
  src/core/flags.cc
  tensor_comprehensions/__init__.py
  tensor_comprehensions/pybinds/pybind_engine.cc
  tensor_comprehensions/tc_unit.py
  test_python/layers/test_dump_cuda.py
  test_python/layers/test_layernorm.py
  test_python/test_debug_init.py
  test_python/test_tc_torch.py
Labels: CLA Signed, review me

#167 Compile caffe2 properly when only WITH_CUDA=0 is passed
  build.sh
Labels: CLA Signed

#173 polyhedral/codegen_*.cc: remove comment about schedule space
  src/core/polyhedral/codegen_cuda.cc
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#171 include/tc/aten/utils-inl.h: mark functions inline
  include/tc/aten/utils-inl.h
Labels: CLA Signed

#181 Fix compilation issue: undefined template
  include/tc/core/polyhedral/schedule_tree_elem.h
  src/core/polyhedral/codegen.cc
Labels: CLA Signed

#180 Fix compilation issue: hides overloaded virtual functions
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#182 emitMappedTensorAccess: use isl AST expression generator
  src/core/polyhedral/codegen_cuda.cc
Labels: CLA Signed

#185 emitTreeSyncCall: drop check for active threads
  src/core/polyhedral/codegen_cuda.cc
Labels: CLA Signed

#192 TC2Isl::Check: drop spurious comment
  test/test_tc2halide.cc
Labels: CLA Signed

#187 Bunch of doc fixes and use correct reduction operators
  docs/source/framework/pytorch_integration/layers_database.rst
  docs/source/framework/pytorch_integration/writing_layers.rst
  tensor_comprehensions/library/layers.yaml
  tensor_comprehensions/tc_unit.py
  test_python/layers/test_avgpool.py
  test_python/layers/test_avgpool_autotune.py
  test_python/layers/test_maxpool.py
  test_python/test_scalar_tc.py
  test_python/test_tc_torch.py
Labels: CLA Signed

#188 Add ccache stats during build time
  .jenkins/build.sh
Labels: CLA Signed

#201 Improve the build script
  build.sh
Labels: CLA Signed

#202 emitHalideExpr: use isl AST expression generator to print expression
  src/core/polyhedral/codegen_cuda.cc
  test/test_mapper.cc
  test/test_mapper_memory_promotion.cc
  test/test_tc_mapper_bugs.cc
Labels: CLA Signed

#210 halide2isl.cc: extractAccess: drop unused variable
  src/core/halide2isl.cc
Labels: CLA Signed

#218 Hotfix update test to latest syntactic changes
  test/test_mapper_memory_promotion.cc
Labels: CLA Signed

#212 Autotuning update
  examples/example_MLP_model.cc
  examples/scripts/AUTOTUNER_COMMANDS
  examples/scripts/autotuner_parallel.sh
Labels: CLA Signed

#189 Document the grammar generating TC ASTs
  include/tc/lang/tree_views.h
Labels: CLA Signed

#203 Add TC format (a pretty printer for AST)
  include/tc/lang/lexer.h
  include/tc/lang/tc_format.h
  include/tc/lang/tree_views.h
  src/lang/CMakeLists.txt
  src/lang/lexer.cc
  src/lang/tc_format.cc
  test/test_lang.cc
Labels: CLA Signed

#206 Genetic tuner: std::abort on SIGTERM
  include/tc/autotuner/genetic_tuning_harness.h
  src/autotuner/genetic_autotuner.cc
  src/autotuner/genetic_tuning_harness.cc
Labels: CLA Signed

#229 Remove the flags check for logging in two places
  src/autotuner/genetic_tuning_harness.cc
  src/core/cuda/cuda_tc_executor.cc
Labels: CLA Signed

#184 emitLLVMKernel: avoid relying on isl set variable names
  include/tc/core/halide2isl.h
  include/tc/core/polyhedral/scop.h
  src/core/halide2isl.cc
  src/core/polyhedral/codegen_llvm.cc
  src/core/polyhedral/scop.cc
Labels: CLA Signed

#54 Temporary fix for library path to unblock folks
  src/core/polyhedral/llvm_jit.cc
Labels: CLA Signed

#223 Bump autotune default options, use small gen=2 for test and remove redundant tests
  tensor_comprehensions/tc_unit.py
  test_python/test_tc_torch.py
Labels: CLA Signed

#219 Parallel CPU mapper
  build.sh
  include/tc/core/polyhedral/codegen_llvm.h
  include/tc/core/polyhedral/llvm_jit.h
  include/tc/core/polyhedral/scop.h
  src/core/polyhedral/codegen_llvm.cc
  src/core/polyhedral/llvm_jit.cc
  test/CMakeLists.txt
  test/test_mapper_tapir.cc
Labels: CLA Signed

#216 Fix tc_lang runtime error in FBcode
  CMakeLists.txt
  include/tc/lang/tree.h
  test/test_lang.cc
Labels: CLA Signed

#231 halide2isl::makeScheduleTree: use isl::schedule for constructing tree
  src/core/halide2isl.cc
Labels: CLA Signed

#239 clean up #219
  src/core/polyhedral/codegen_llvm.cc
Labels: CLA Signed

#238 src/lang/lexer.cc: compare const char* strings using strcmp
  src/lang/lexer.cc
Labels: CLA Signed
